server {
    listen 80;
    listen [::]:80;

    server_name www.clipromocoes.com.br clipromocoes.com.br;

    root /usr/share/nginx/html/cafe;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name www.softweaver.com.br softweaver.com.br;

    root /usr/share/nginx/html/softweaver;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}